colas/urls.py
from django.urls import path
from .views import Colas

app_name = 'colas'
urlpatterns = [
    path('', Colas.as_view(), name='colas'),
]

montecarlo/urls.py
from django.urls import path
from .views import Montecarlo, Montecarlo2
app_name = 'montecarlo'

urlpatterns = [
    path('product1/', Montecarlo.as_view(), name='montecarlo'),
    path('product2/', Montecarlo2.as_view(), name='montecarlo2'),
]

tp5/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views import generic
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('', generic.TemplateView.as_view(template_name='colas/index.html'), name='index'),
                  path('colas/', include('colas.urls')),

              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/header/header.html
<!-- Navbar-->
{% load static %}

<div class="d-flex flex-column flex-md-row align-items-center p-3 pr-md-4 mb-3 bg-white border-bottom shadow-sm h5">

	<div class="my-0 mr-md-auto">
		<img width=40 src="{% static 'bar-graph.ico' %}">
	</div>
	<nav class="my-2 my-md-0 mr-4">
		<!--Opciones de un usuario staff-->
		<a class="p-2 text-dark" href="{% url 'colas:colas' %}">Colas</a>
		<a class="p-2 text-dark" href="{% url 'index' %}">Inicio</a>


	</nav>
</div>

templates/header/hello_user.html
<h5 class="my-0 mr-md-auto font-weight-normal">
    {% if request.user.is_authenticated %}
    Hola {{request.user.username|capfirst}}!
    {% endif %}
</h5>

templates/header/login_header.html
<!--Opciones de un usuario staff-->
{% if not request.user.is_authenticated %}
<a class="p-2 text-dark" href="{% url 'accounts:login' %}">Iniciar sesion</a>
{% endif %}

templates/header/options_header.html
<!--Opciones de un usuario staff-->
<div class="btn-group">
	<button type="button" class="btn btn-lg dropdown-toggle" data-toggle="dropdown" aria-haspopup="true"
			aria-expanded="false">Distribuciones</button>
	<div class="dropdown-menu">
		<a class="dropdown-item h6" href="{% url 'montecarlo:montecarlo' %}">Montecarlo</a>
	</div>
</div>