montecarlo/urls.py
from django.urls import path
from .views import Montecarlo, Montecarlo2
app_name = 'montecarlo'

urlpatterns = [
    path('product1/', Montecarlo.as_view(), name='montecarlo'),
    path('product2/', Montecarlo2.as_view(), name='montecarlo2'),
]

tp5/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views import generic
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('', generic.TemplateView.as_view(template_name='colas/index.html'), name='index'),
                  path('colas/', include('colas.urls')),

              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

montecarlo/models.py
from django.db import models

# Create your models here.

montecarlo/forms.py
from django import forms
from crispy_forms.helper import FormHelper


class ParametersForm(forms.Form):
    costo = forms.IntegerField(label='costo', initial=10, min_value=0)
    precio_venta = forms.IntegerField(label='precio de venta', initial=16, min_value=0)
    tiempo_reposicion = forms.IntegerField(label='tiempo de reposicion', initial=3, min_value=1)
    cant_a_reponer = forms.IntegerField(label='cantidad a reponer', initial=15, min_value=0)
    stock_inicial = forms.IntegerField(label='stock inicial', initial=15, min_value=0)
    vencimiento = forms.IntegerField(label='vencimiento', initial=2, min_value=1, required=False)
    cant_iteraciones = forms.IntegerField(label='cantidad de dias', min_value=1, initial=15)

    # Permite elegir si utlizar los numeros aleatorios del ejercicio o los random
    PSEUDO_CHOICES = ((True, 'Si'), (False, 'No'))
    pseudoaleatorio = forms.ChoiceField(label='Utilizar numeros del ejercicio?', choices=PSEUDO_CHOICES,
                                        initial=PSEUDO_CHOICES[0])
    recupero = forms.IntegerField(label='valor de recupero', initial=0, min_value=0)

    def __init__(self, *args, **kwargs):
        super(ParametersForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        # self.helper.form_show_labels = False
        self.helper.form_tag = False

class ParametersForm2(ParametersForm):
    costo = forms.IntegerField(label='costo', initial=13, min_value=0)
    vencimiento = forms.IntegerField(label='vencimiento', min_value=1, required=False)
    recupero = forms.IntegerField(label='valor de recupero', initial=11, min_value=0)

montecarlo/views.py
from django.shortcuts import render
from django.views import generic
from .montecarlo import Producto, ProductoConVencimiento, ProductoSinVencimiento
from .forms import ParametersForm, ParametersForm2
# Create your views here.

class Montecarlo(generic.FormView):
    form_class = ParametersForm
    template_name = 'montecarlo/forms/montecarlo.html'

    def form_valid(self, form):
        if form.cleaned_data['pseudoaleatorio'] == 'True':
            num_pseudoaleatorios = [0.94, 0.74, 0.62, 0.11, 0.17, 0.66, 0.54, 0.30, 0.69, 0.08,
           0.27, 0.13, 0.80, 0.10, 0.54, 0.60, 0.49, 0.78, 0.66, 0.44]
        else:
            num_pseudoaleatorios = []

        if form.cleaned_data['vencimiento'] is None:
            product = ProductoSinVencimiento(
                c=form.cleaned_data['costo'],
                p=form.cleaned_data['precio_venta'],
                tr=form.cleaned_data['tiempo_reposicion'],
                cr=form.cleaned_data['cant_a_reponer'],
                si=form.cleaned_data['stock_inicial'],
                r=form.cleaned_data['recupero'],
                num_pseudoaleatorios=num_pseudoaleatorios
            )
        else:
            product = ProductoConVencimiento(
                c=form.cleaned_data['costo'],
                p=form.cleaned_data['precio_venta'],
                tr=form.cleaned_data['tiempo_reposicion'],
                cr=form.cleaned_data['cant_a_reponer'],
                si=form.cleaned_data['stock_inicial'],
                # Se agrega 1 porque segun el enunciado ingresamos los dias que se vence despues de haber llegado
                # y en la libreria se consideria dias de vencimiento a partir de que llego
                v=form.cleaned_data['vencimiento'] + 1,
                num_pseudoaleatorios=num_pseudoaleatorios
            )
        iteraciones = form.cleaned_data['cant_iteraciones']
        ganancia = product.simular(iteraciones)

        context = {}
        context['ganancia'] = ganancia
        context['ganancia_media'] = round(ganancia / iteraciones, 2)
        context['form'] = form

        if len(product.tabla) >= 30:
            context['tabla'] = product.tabla[0:30]
            if len(product.tabla) >= 40:
                context['tabla_fin'] = product.tabla[-10:]
            else:
                context['tabla_fin'] = product.tabla[30:]
        else:
            context['tabla'] = product.tabla

        return render(self.request, template_name=self.template_name, context=context)


class Montecarlo2(Montecarlo):
    form_class = ParametersForm2

montecarlo/templates/montecarlo/forms/montecarlo.html
{% extends 'montecarlo/base_form.html' %}
{% load crispy_forms_tags %}
{% block form %}
<h1 class="text-center">Montecarlo</h1>
    <hr>
<div class="text-right">
    <a class="btn btn-lg btn-outline-primary" href="{% url 'montecarlo:montecarlo' %}">Producto 1</a>
    <a class="btn btn-lg btn-outline-success" href="{% url 'montecarlo:montecarlo2' %}">Producto 2</a>
</div>
<br>
    <div class="row">
        <div class="col-3">
            {{ form.precio_venta|as_crispy_field }}
        </div>
        <div class="col-3">
            {{ form.costo|as_crispy_field }}
        </div>
        <div class="col-3">
            {{ form.vencimiento|as_crispy_field }}
        </div>
        <div class="col-3">
            {{ form.recupero|as_crispy_field }}
        </div>
    </div>

    <h3>Reposicion</h3>
    <div class="row">
         <div class="col-4">
            {{ form.tiempo_reposicion|as_crispy_field }}
        </div>
        <div class="col-4">
            {{ form.cant_a_reponer|as_crispy_field }}
        </div>
        <div class="col-4">
            {{ form.stock_inicial|as_crispy_field }}
        </div>
    </div>

    <h3>Simulacion</h3>
    <div class="row">
        <div class="col-4">
            {{ form.cant_iteraciones|as_crispy_field }}
        </div>
        <div class="col-4">
            {{ form.pseudoaleatorio|as_crispy_field }}
        </div>
    </div>

<div class="text-right">
    <button class="btn btn-lg btn-primary">Calcular</button>
</div>

{% if ganancia %}
<hr>
<hr>
<div class="text-center">
    <h3>Ganancias totales: ${{ganancia}}</h3>
    <h3>Ganancia media por dia: ${{ganancia_media}}</h3>
</div>
<hr>
<div>
    <!-- Tabla del proceso de montecarlo-->
    {% include 'montecarlo/snippets/table.html' with tabla=tabla %}

    {% if tabla_fin %}
    <a class="btn btn-block btn-outline-dark" data-toggle="collapse" href="#collapseExample" role="button" aria-expanded="false" aria-controls="collapseExample">
        <strong>...</strong>
    </a>

    <div class="collapse.show" id="collapseExample">
        <br>
    {% include 'montecarlo/snippets/table.html' with tabla=tabla_fin %}
    </div>
    {% endif %}
</div>

{% endif %}

{% endblock form %}